
  {
    asking_price: 250000.00,
    cash_flow: 75000.00,
    gross_revenue: 300000.00,
    ebitda: 90000.00,
    ffe: 50000.00,
    inventory: 20000.00,
    rent: 12000.00,
    established: 2010,
    business_description: "A thriving business in the heart of downtown Kansas City.",
    detail_information: {
      location: "123 Main Street, Kansas City, MO",
      inventory: "Stored locally in warehouse facilities.",
      real_estate: "Owns the building",
      building_sf: 10000,
      lease_expiration: "N/A",
      employees: 12,
      ffe_kansas: "Fully equipped with modern machinery and tools.",
      facilities: "State-of-the-art facilities with ample parking.",
      competition: "Limited local competition.",
      growth_expansion: "Potential for expansion into neighboring states.",
      support_training: "Seller will provide training and support.",
      reason_for_selling: "Owner retiring.",
      franchise: "Independent business."
    },
    business_location_description: "Prime location with high foot traffic."
  },
  {
    asking_price: 180000.00,
    cash_flow: 50000.00,
    gross_revenue: 250000.00,
    ebitda: 70000.00,
    ffe: 40000.00,
    inventory: 15000.00,
    rent: 10000.00,
    established: 2008,
    business_description: "Specialty restaurant known for its unique cuisine and loyal customer base.",
    detail_information: {
      location: "456 Elm Street, Kansas City, KS",
      inventory: "Local and imported ingredients stored onsite.",
      real_estate: "Leased premises.",
      building_sf: 5000,
      lease_expiration: "2025",
      employees: 8,
      ffe_kansas: "Fully furnished with dining and kitchen equipment.",
      facilities: "Cozy dining area with outdoor seating.",
      competition: "Established competitors nearby.",
      growth_expansion: "Potential to franchise the concept.",
      support_training: "Chef-owner will provide recipes and training.",
      reason_for_selling: "Relocation to another state.",
      franchise: "Not a franchise."
    },
    business_location_description: "Located in a trendy neighborhood."
  },
  {
    asking_price: 300000.00,
    cash_flow: 100000.00,
    gross_revenue: 400000.00,
    ebitda: 120000.00,
    ffe: 60000.00,
    inventory: 25000.00,
    rent: 15000.00,
    established: 2015,
    business_description: "E-commerce business selling handmade artisan goods worldwide.",
    detail_information: {
      location: "Online business based in Kansas City, MO",
      inventory: "Stored in fulfillment centers across the country.",
      real_estate: "Operates from a home office.",
      building_sf: "N/A",
      lease_expiration: "N/A",
      employees: 5,
      ffe_kansas: "Utilizes digital tools and software.",
      facilities: "Virtual office setup with remote team.",
      competition: "Competes with other online artisan marketplaces.",
      growth_expansion: "Opportunity to expand product lines.",
      support_training: "Seller will provide online marketing strategies.",
      reason_for_selling: "Owner pursuing other ventures.",
      franchise: "Not applicable."
    },
    business_location_description: "Digital business with global reach."
  },
  {
    asking_price: 150000.00,
    cash_flow: 40000.00,
    gross_revenue: 200000.00,
    ebitda: 60000.00,
    ffe: 30000.00,
    inventory: 10000.00,
    rent: 8000.00,
    established: 2012,
    business_description: "Family-owned bakery known for its artisan breads and pastries.",
    detail_information: {
      location: "789 Oak Avenue, Overland Park, KS",
      inventory: "Baked goods made fresh daily on-site.",
      real_estate: "Leased bakery storefront.",
      building_sf: 3000,
      lease_expiration: "2023",
      employees: 6,
      ffe_kansas: "Equipped with industrial ovens and baking equipment.",
      facilities: "Warm and inviting bakery atmosphere.",
      competition: "Local competition from other bakeries.",
      growth_expansion: "Potential to supply to local cafes and restaurants.",
      support_training: "Owner will provide recipes and baking techniques.",
      reason_for_selling: "Owner retiring.",
      franchise: "Independent bakery."
    },
    business_location_description: "Located in a bustling shopping district."
  },
  {
    asking_price: 280000.00,
    cash_flow: 90000.00,
    gross_revenue: 350000.00,
    ebitda: 110000.00,
    ffe: 55000.00,
    inventory: 18000.00,
    rent: 13000.00,
    established: 2016,
    business_description: "Fitness center offering a variety of classes and personal training services.",
    detail_information: {
      location: "101 Pine Street, Kansas City, MO",
      inventory: "Fitness equipment and supplies in excellent condition.",
      real_estate: "Leased gym facility.",
      building_sf: 8000,
      lease_expiration: "2024",
      employees: 10,
      ffe_kansas: "Includes cardio machines, weights, and exercise mats.",
      facilities: "Spacious gym area with locker rooms and showers.",
      competition: "Competes with other local gyms and fitness centers.",
      growth_expansion: "Potential to add more classes and programs.",
      support_training: "Owner will provide fitness training methods.",
      reason_for_selling: "Owner relocating out of state.",
      franchise: "Independent fitness center."
    },
    business_location_description: "Convenient location with ample parking."
  },
  {
    asking_price: 200000.00,
    cash_flow: 60000.00,
    gross_revenue: 280000.00,
    ebitda: 80000.00,
    ffe: 45000.00,
    inventory: 12000.00,
    rent: 10000.00,
    established: 2014,
    business_description: "IT consulting firm specializing in cybersecurity solutions.",
    detail_information: {
      location: "222 Broad Street, Overland Park, KS",
      inventory: "Digital security tools and software licenses.",
      real_estate: "Leased office space.",
      building_sf: 5000,
      lease_expiration: "2023",
      employees: 7,
      ffe_kansas: "Equipped with high-end servers and networking hardware.",
      facilities: "Modern office setup with conference rooms.",
      competition: "Competes with other IT consulting firms.",
      growth_expansion: "Potential to expand into managed services.",
      support_training: "Seller will provide cybersecurity training.",
      reason_for_selling: "Owner pursuing a different career path.",
      franchise: "Not a franchise."
    },
    business_location_description: "Professional office environment."
  },
  {
    asking_price: 320000.00,
    cash_flow: 110000.00,
    gross_revenue: 420000.00,
    ebitda: 130000.00,
    ffe: 70000.00,
    inventory: 30000.00,
    rent: 18000.00,
    established: 2017,
    business_description: "Pet grooming salon and retail store catering to pet lovers.",
    detail_information: {
      location: "555 Maple Avenue, Kansas City, MO",
      inventory: "Pet grooming supplies and pet accessories.",
      real_estate: "Leased retail space.",
      building_sf: 4000,
      lease_expiration: "2025",
      employees: 9,
      ffe_kansas: "Includes grooming tables, baths, and pet drying stations.",
      facilities: "Pet-friendly environment with waiting area.",
      competition: "Competes with other local pet grooming salons.",
      growth_expansion: "Potential to add pet daycare services.",
      support_training: "Owner will provide grooming techniques and customer service training.",
      reason_for_selling: "Owner relocating to another state.",
      franchise: "Independent pet grooming business."
    },
    business_location_description: "Pet-friendly neighborhood with parks nearby."
  },
  {
    asking_price: 270000.00,
    cash_flow: 80000.00,
    gross_revenue: 370000.00,
    ebitda: 100000.00,
    ffe: 60000.00,
    inventory: 22000.00,
    rent: 15000.00,
    established: 2013,
    business_description: "Auto repair shop known for its quality service and customer satisfaction.",
    detail_information: {
      location: "333 Oak Street, Overland Park, KS",
      inventory: "Automotive parts and supplies in stock.",
      real_estate: "Leased automotive repair shop.",
      building_sf: 6000,
      lease_expiration: "2024",
      employees: 8,
      ffe_kansas: "Equipped with lifts, diagnostic tools, and repair equipment.",
      facilities: "Clean and organized workshop area.",
      competition: "Competes with other local auto repair